[package]
name = "Simple_Rust_GPU_Raytracer"
version = "0.1.0"
authors = ["Bjarke Pedersen <contact@bjarke.io>"]

[dependencies]
minifb = "*"
rgb = "*"
rand = "*"
cgmath = "*"
rayon = "*"
ordered-float = "*"
time = "*"
